id: jaipur
name: Jaipur
state: Rajasthan
country: India
iso_country: IN
center: !!python/tuple
- 26.915458
- 75.818982
bbox: !!python/tuple
- 75.658982
- 26.755458
- 75.978982
- 27.075458
alternate_names: []
timezone: Asia/Kolkata
osm_place_id: 246456501
wikidata_id: null
dataset_version: 1.0.0
generated_at: '2026-09-19T09:40:53.216499+00:00'
